apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pokemon-app-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: server
  endpoints:
  - port: http
    path: /metrics