name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: eyalsegaldev/flask-pokemon-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Create .kube directory
      run: mkdir -p $HOME/.kube

    - name: Set up Kubeconfig
      run: echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

    - name: Verify Kubeconfig Environment Variable
      run: cat $HOME/.kube/config

    - name: Set KUBECONFIG Environment Variable
      env:
        KUBECONFIG: $HOME/.kube/config
      run: echo "KUBECONFIG is set"

    - name: Deploy to Kubernetes
      env:
        KUBECONFIG: $HOME/.kube/config
      run: |
        kubectl apply -f k8s/configmap.yaml
        kubectl apply -f k8s/server-deployment.yaml
        kubectl apply -f k8s/server-service.yaml
        kubectl apply -f k8s/hpa.yaml
        kubectl apply -f k8s/grafana-deployment.yaml